/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllCountryView: typeof import('./src/components/AllCountryView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerifyPoints: typeof import('./src/components/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./src/components/Verify/VerifySlide.vue')['default']
    VerifyView: typeof import('./src/components/VerifyView.vue')['default']
  }
}
